language: elixir
elixir:
  - 1.6.0

env:
  - MIX_ENV=test

install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix do deps.get, deps.compile

script:
  - MIX_ENV=test mix coveralls.travis test/*

notifications:
email: false
